name: maestro
author: Piotr Majkrzak <piotr@majkrzak.dev>
license: ISC
github: majkrzak/maestro

dependencies:
- base
- network-uri
- text
- aeson
- bytestring
- unordered-containers

default-extensions:
- OverloadedStrings
- DeriveGeneric
- DeriveAnyClass
- FlexibleContexts
- FlexibleInstances
- ConstraintKinds
- UndecidableInstances
- DefaultSignatures
- DeriveDataTypeable
- TypeOperators

ghc-options:
- -Wall
- -O2

library:
  source-dirs: src

tests:
  unit:
    main: Spec.hs
    source-dirs: tests/unit
    dependencies:
    - maestro
    - hspec

